# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- charandev-cicd

pool:
  default

resources:
- repo: self

variables:
  mytag: 'myimage-$(Build.BuildId)'

steps:
# - task: DockerInstaller@0
#   inputs:
#     dockerVersion: '17.09.0-ce'
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-connection'
    repository: 'charankumarcpl/pipeline'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(mytag)

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-connection'
    repository: 'charankumarcpl/pipeline'
    command: 'push'
    tags:   $(mytag)