# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- charandev-cicd

pool:
  default

resources:
- repo: self

variables:
  mytag: 'myimage-$(Build.BuildId)'

steps:
# - task: DockerInstaller@0
#   inputs:
#     dockerVersion: '17.09.0-ce'
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-connection'
    repository: 'charankumarcpl/pipeline'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(mytag)

- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-connection'
    repository: 'charankumarcpl/pipeline'
    command: 'push'
    tags:   $(mytag)

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '3e2e9c6a-60da-4871-94ef-2ab229f1ad6c/57e284b8-d2a4-4caa-b2c3-dddae9e352bd'
    vstsFeedPackagePublish: 'sample-artifact-package'
    versionOption: 'patch'

- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '3e2e9c6a-60da-4871-94ef-2ab229f1ad6c/f48f7818-bd03-4823-94a4-9b079a2eac17'
    vstsFeedPackagePublish: 'myfrstartifact'
    versionOption: 'patch'